export interface Tool {
  id: string;
  name: string;
  tagline: string;
  description: string;
  websiteUrl: string;
  category: string;
  tags: string[];
  pricingType: "free" | "freemium" | "paid" | "opensource";
  isChinaAvailable: boolean;
  isChineseSupported: boolean;
  rating: number;
  ratingCount: number;
  viewCount: number;
  screenshots: string[];
  createdAt: string;
  // AI质量评估字段
  aiQualityScore?: number; // AI质量评分 (0-10)
  aiQualityReview?: any; // AI质量评估详细结果JSON
  aiReviewDate?: string; // AI审核时间
  aiReviewNotes?: string; // AI审核备注
}

export const categories = [
  { id: "all", name: "全部", icon: "🔥" },
  { id: "chat", name: "对话", icon: "📝" },
  { id: "writing", name: "写作", icon: "✍️" },
  { id: "image", name: "绘画", icon: "🎨" },
  { id: "video", name: "视频", icon: "🎬" },
  { id: "audio", name: "音频", icon: "🎵" },
  { id: "coding", name: "编程", icon: "💻" },
  { id: "search", name: "搜索", icon: "🔍" },
  { id: "office", name: "办公", icon: "📊" },
  { id: "agent", name: "Agent", icon: "🤖" },
  { id: "dev", name: "开发", icon: "🔧" },
] as const;

export const categoryColorMap: Record<string, string> = {
  chat: "hsl(217, 91%, 60%)",
  writing: "hsl(142, 71%, 45%)",
  image: "hsl(262, 83%, 58%)",
  video: "hsl(0, 84%, 60%)",
  audio: "hsl(25, 95%, 53%)",
  coding: "hsl(187, 85%, 43%)",
  search: "hsl(45, 93%, 47%)",
  office: "hsl(231, 48%, 48%)",
  agent: "hsl(330, 81%, 60%)",
  dev: "hsl(215, 14%, 46%)",
};

export const pricingLabels: Record<string, string> = {
  free: "免费",
  freemium: "免费增值",
  paid: "付费",
  opensource: "开源",
};

export const tools: Tool[] = [
  // ===== 对话 (chat) =====
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI开发的智能对话助手，支持多轮对话、代码生成、文本创作等多种任务",
    description: `## ChatGPT 简介\n\nChatGPT 是由 OpenAI 开发的大语言模型对话系统，基于 GPT-4 架构。它能够理解和生成自然语言，进行多轮对话交互。\n\n### 核心功能\n- 智能对话与问答\n- 代码编写与调试\n- 文案创作与翻译\n- 数据分析与总结\n\n### 使用场景\n适用于日常问答、学习辅助、编程开发、内容创作等多种场景。\n\n### 优缺点\n- ✅ 功能全面，响应速度快\n- ✅ 支持插件和GPTs扩展\n- ❌ 免费版有使用限制\n- ❌ 国内需要翻墙访问`,
    websiteUrl: "https://chat.openai.com",
    category: "chat",
    tags: ["GPT", "对话", "写作", "编程", "AI助手"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.8,
    ratingCount: 12580,
    viewCount: 98234,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-01-15",
  },
  {
    id: "claude",
    name: "Claude",
    tagline: "Anthropic推出的AI助手，擅长长文本分析、逻辑推理和安全对话",
    description: `## Claude 简介\n\nClaude 是 Anthropic 公司开发的AI对话助手，以安全性和长上下文处理能力著称。\n\n### 核心功能\n- 超长文本理解（支持200K上下文）\n- 代码分析与生成\n- 文档总结与分析\n- 多语言翻译\n\n### 使用场景\n特别适合处理长文档、学术论文分析、代码审查等需要深度理解的任务。\n\n### 优缺点\n- ✅ 长文本处理能力强\n- ✅ 回答准确且安全\n- ❌ 免费版额度有限\n- ❌ 国内需要翻墙`,
    websiteUrl: "https://claude.ai",
    category: "chat",
    tags: ["Claude", "对话", "长文本", "推理"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.7,
    ratingCount: 8432,
    viewCount: 67891,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-20",
  },
  {
    id: "wenxin",
    name: "文心一言",
    tagline: "百度推出的知识增强大语言模型，深度整合中文语境和百度搜索生态",
    description: `## 文心一言简介\n\n文心一言是百度推出的生成式AI产品，基于文心大模型。\n\n### 核心功能\n- 中文对话理解\n- 文案生成与润色\n- 图片生成\n- 知识问答\n\n### 使用场景\n适合中文内容创作、知识查询、日常助手等场景。\n\n### 优缺点\n- ✅ 中文理解能力强\n- ✅ 国内直接可用\n- ❌ 英文能力相对较弱\n- ❌ 部分高级功能需付费`,
    websiteUrl: "https://yiyan.baidu.com",
    category: "chat",
    tags: ["文心", "对话", "中文", "百度"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 9876,
    viewCount: 54321,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-16",
  },
  {
    id: "gemini",
    name: "Gemini",
    tagline: "Google DeepMind打造的多模态AI模型，支持文字、图像、代码等多种输入",
    description: `## Gemini 简介\n\nGemini 是 Google DeepMind 推出的多模态AI模型。\n\n### 核心功能\n- 多模态理解（文字+图像+视频）\n- 代码生成与分析\n- 创意写作\n- 实时信息检索\n\n### 使用场景\n适用于需要多模态输入的复杂任务。\n\n### 优缺点\n- ✅ 多模态能力强\n- ✅ 与Google生态整合\n- ❌ 国内无法访问\n- ❌ 中文能力有待提升`,
    websiteUrl: "https://gemini.google.com",
    category: "chat",
    tags: ["Gemini", "Google", "多模态", "对话"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 6543,
    viewCount: 45678,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-12-06",
  },
  {
    id: "kimi",
    name: "Kimi",
    tagline: "月之暗面推出的智能助手，支持200万字超长上下文，擅长文档分析",
    description: `## Kimi 简介\n\nKimi 是月之暗面公司推出的AI助手，以超长上下文闻名。\n\n### 核心功能\n- 200万字超长上下文\n- 文件解析与总结\n- 联网搜索\n- 多轮对话\n\n### 使用场景\n适合长文档分析、论文阅读、资料整理等。\n\n### 优缺点\n- ✅ 超长上下文\n- ✅ 国内直接可用\n- ✅ 免费使用\n- ❌ 高峰期可能排队`,
    websiteUrl: "https://kimi.moonshot.cn",
    category: "chat",
    tags: ["Kimi", "长文本", "文档", "免费"],
    pricingType: "free",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 7654,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-10-09",
  },
  // ===== 写作 (writing) =====
  {
    id: "jasper",
    name: "Jasper",
    tagline: "企业级AI写作平台，提供营销文案、博客、社交媒体等多场景内容生成",
    description: `## Jasper 简介\n\nJasper 是面向企业的AI内容生成平台。\n\n### 核心功能\n- 营销文案自动生成\n- 多语言内容创作\n- 品牌语调定制\n- SEO优化建议\n\n### 使用场景\n适合营销团队、内容运营、社交媒体管理等。\n\n### 优缺点\n- ✅ 模板丰富\n- ✅ 品牌一致性好\n- ❌ 价格较高\n- ❌ 中文生成质量一般`,
    websiteUrl: "https://www.jasper.ai",
    category: "writing",
    tags: ["写作", "营销", "文案", "SEO"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.4,
    ratingCount: 3456,
    viewCount: 23456,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-02-10",
  },
  {
    id: "copyai",
    name: "Copy.ai",
    tagline: "AI驱动的营销文案生成工具，快速生成广告语、邮件和社交媒体内容",
    description: `## Copy.ai 简介\n\nCopy.ai 是一款AI文案生成工具，专注于营销内容。\n\n### 核心功能\n- 广告文案生成\n- 邮件营销内容\n- 社交媒体帖子\n- 产品描述\n\n### 使用场景\n适合需要快速产出营销内容的团队和个人。\n\n### 优缺点\n- ✅ 上手简单\n- ✅ 有免费额度\n- ❌ 长文本质量一般\n- ❌ 中文支持有限`,
    websiteUrl: "https://www.copy.ai",
    category: "writing",
    tags: ["文案", "营销", "邮件", "广告"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.2,
    ratingCount: 2345,
    viewCount: 18765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-01-20",
  },
  {
    id: "mita-writing",
    name: "秘塔写作猫",
    tagline: "国产AI写作助手，支持论文润色、文案改写、语法纠错等中文写作场景",
    description: `## 秘塔写作猫简介\n\n秘塔写作猫是国产AI写作工具，专注中文写作场景。\n\n### 核心功能\n- 文章润色与改写\n- 语法纠错\n- 论文降重\n- AI续写\n\n### 使用场景\n适合学生论文、公文写作、自媒体创作等。\n\n### 优缺点\n- ✅ 中文优化好\n- ✅ 国内直接用\n- ✅ 有免费额度\n- ❌ 高级功能需付费`,
    websiteUrl: "https://xiezuocat.com",
    category: "writing",
    tags: ["写作", "中文", "润色", "论文"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.1,
    ratingCount: 4567,
    viewCount: 32100,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-04-15",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    tagline: "集成在Notion中的AI写作助手，支持文档总结、头脑风暴和内容生成",
    description: `## Notion AI 简介\n\nNotion AI 是集成在 Notion 工作空间中的AI助手。\n\n### 核心功能\n- 文档自动总结\n- 内容生成与改写\n- 翻译\n- 头脑风暴\n\n### 使用场景\n适合已使用Notion的团队，无缝融入工作流。\n\n### 优缺点\n- ✅ 与Notion深度集成\n- ✅ 使用方便\n- ❌ 需要Notion付费版\n- ❌ 独立使用受限`,
    websiteUrl: "https://www.notion.so/product/ai",
    category: "writing",
    tags: ["Notion", "写作", "笔记", "协作"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 5678,
    viewCount: 28900,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-02-22",
  },
  // ===== 绘画 (image) =====
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "顶级AI绘画工具，通过文本描述生成高质量艺术图片，风格多样",
    description: `## Midjourney 简介\n\nMidjourney 是目前最受欢迎的AI图像生成工具之一。\n\n### 核心功能\n- 文本生成图像\n- 多种艺术风格\n- 图像变体与混合\n- 高分辨率输出\n\n### 使用场景\n适合设计师、艺术家、内容创作者等。\n\n### 优缺点\n- ✅ 图片质量极高\n- ✅ 艺术风格丰富\n- ❌ 需要通过Discord使用\n- ❌ 需付费订阅`,
    websiteUrl: "https://www.midjourney.com",
    category: "image",
    tags: ["绘画", "艺术", "图像生成", "设计"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.9,
    ratingCount: 15678,
    viewCount: 120345,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-07-12",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "开源AI图像生成模型，可本地部署，支持高度自定义和社区扩展",
    description: `## Stable Diffusion 简介\n\n开源的文本到图像生成模型，由 Stability AI 开发。\n\n### 核心功能\n- 文本生成图像\n- 图像编辑与修复\n- ControlNet精确控制\n- LoRA模型微调\n\n### 使用场景\n适合有技术背景的用户，需要高度定制化的图像生成。\n\n### 优缺点\n- ✅ 完全开源免费\n- ✅ 可本地运行\n- ❌ 需要GPU\n- ❌ 上手有门槛`,
    websiteUrl: "https://stability.ai",
    category: "image",
    tags: ["开源", "绘画", "本地部署", "SD"],
    pricingType: "opensource",
    isChinaAvailable: true,
    isChineseSupported: false,
    rating: 4.6,
    ratingCount: 11234,
    viewCount: 89012,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-08-22",
  },
  {
    id: "dalle3",
    name: "DALL·E 3",
    tagline: "OpenAI最新图像生成模型，理解复杂提示词，集成于ChatGPT中",
    description: `## DALL·E 3 简介\n\nDALL·E 3 是 OpenAI 推出的第三代图像生成模型。\n\n### 核心功能\n- 精确理解文本描述\n- 高质量图像生成\n- 与ChatGPT集成\n- 支持图像编辑\n\n### 使用场景\n适合需要快速生成插图、概念图的用户。\n\n### 优缺点\n- ✅ 理解能力强\n- ✅ 与ChatGPT无缝集成\n- ❌ 风格相对单一\n- ❌ 需ChatGPT Plus`,
    websiteUrl: "https://openai.com/dall-e-3",
    category: "image",
    tags: ["DALL·E", "OpenAI", "图像生成", "AI绘画"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 7890,
    viewCount: 67890,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-09-20",
  },
  {
    id: "jimeng",
    name: "即梦AI",
    tagline: "字节跳动推出的AI创作平台，支持图片和视频生成，国内可直接使用",
    description: `## 即梦AI简介\n\n即梦AI是字节跳动推出的AI创意平台。\n\n### 核心功能\n- AI图片生成\n- AI视频生成\n- 多种风格模板\n- 社区分享\n\n### 使用场景\n适合社交媒体创作、短视频制作等。\n\n### 优缺点\n- ✅ 国内直接可用\n- ✅ 有免费额度\n- ✅ 中文理解好\n- ❌ 风格偏网红化`,
    websiteUrl: "https://jimeng.jianying.com",
    category: "image",
    tags: ["即梦", "字节", "绘画", "国产"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.2,
    ratingCount: 6789,
    viewCount: 45678,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-01-15",
  },
  // ===== 视频 (video) =====
  {
    id: "runway",
    name: "Runway",
    tagline: "领先的AI视频生成和编辑平台，支持文本/图片生成视频，专业级效果",
    description: `## Runway 简介\n\nRunway 是AI视频生成领域的领军产品。\n\n### 核心功能\n- Gen-2/Gen-3文本生成视频\n- 图片动画化\n- 视频编辑与特效\n- 背景移除\n\n### 使用场景\n适合视频创作者、影视后期、广告制作等。\n\n### 优缺点\n- ✅ 视频质量高\n- ✅ 工具全面\n- ❌ 价格较贵\n- ❌ 国内需翻墙`,
    websiteUrl: "https://runwayml.com",
    category: "video",
    tags: ["视频", "生成", "编辑", "特效"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.6,
    ratingCount: 5432,
    viewCount: 56789,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-15",
  },
  {
    id: "pika",
    name: "Pika",
    tagline: "简单易用的AI视频生成工具，一键将文字和图片转化为动态视频",
    description: `## Pika 简介\n\nPika 是一款简洁的AI视频生成工具。\n\n### 核心功能\n- 文本生成视频\n- 图片转视频\n- 视频风格转换\n- 视频编辑\n\n### 使用场景\n适合社交媒体内容创作、快速原型制作。\n\n### 优缺点\n- ✅ 操作简单\n- ✅ 有免费额度\n- ❌ 视频时长受限\n- ❌ 国内需翻墙`,
    websiteUrl: "https://pika.art",
    category: "video",
    tags: ["视频", "生成", "简单", "创作"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.3,
    ratingCount: 3456,
    viewCount: 34567,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-06-29",
  },
  {
    id: "kling",
    name: "可灵",
    tagline: "快手推出的AI视频生成大模型，支持最长2分钟1080p高质量视频生成",
    description: `## 可灵简介\n\n可灵是快手推出的AI视频生成模型。\n\n### 核心功能\n- 文本/图片生成视频\n- 最长2分钟视频\n- 1080p高清输出\n- 运动控制\n\n### 使用场景\n适合短视频创作、广告制作等。\n\n### 优缺点\n- ✅ 国内直接可用\n- ✅ 视频质量高\n- ✅ 时长较长\n- ❌ 排队时间长`,
    websiteUrl: "https://klingai.kuaishou.com",
    category: "video",
    tags: ["可灵", "快手", "视频生成", "国产"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.4,
    ratingCount: 4567,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-06-06",
  },
  // ===== 音频 (audio) =====
  {
    id: "suno",
    name: "Suno",
    tagline: "AI音乐生成平台，输入文字描述即可自动作词作曲，生成完整歌曲",
    description: `## Suno 简介\n\nSuno 是一款革命性的AI音乐创作工具。\n\n### 核心功能\n- 文本生成完整歌曲\n- 自动作词作曲\n- 多种音乐风格\n- 人声合成\n\n### 使用场景\n适合音乐爱好者、内容创作者、独立音乐人。\n\n### 优缺点\n- ✅ 生成质量惊人\n- ✅ 操作简单\n- ❌ 商用授权贵\n- ❌ 风格控制有限`,
    websiteUrl: "https://suno.com",
    category: "audio",
    tags: ["音乐", "歌曲", "作曲", "AI音乐"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.7,
    ratingCount: 8765,
    viewCount: 76543,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-09-12",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    tagline: "专业AI语音合成平台，提供逼真的文字转语音和声音克隆服务",
    description: `## ElevenLabs 简介\n\nElevenLabs 是领先的AI语音合成平台。\n\n### 核心功能\n- 高质量文本转语音\n- 声音克隆\n- 多语言支持\n- 情感语调控制\n\n### 使用场景\n适合有声书制作、视频配音、播客等。\n\n### 优缺点\n- ✅ 语音质量极高\n- ✅ 声音克隆逼真\n- ❌ 免费额度少\n- ❌ 中文效果一般`,
    websiteUrl: "https://elevenlabs.io",
    category: "audio",
    tags: ["语音", "TTS", "配音", "克隆"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.6,
    ratingCount: 4321,
    viewCount: 34567,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-01-30",
  },
  {
    id: "udio",
    name: "Udio",
    tagline: "新一代AI音乐生成工具，音质清晰，支持多种流派和精细的风格控制",
    description: `## Udio 简介\n\nUdio 是新兴的AI音乐生成平台。\n\n### 核心功能\n- 高质量音乐生成\n- 精细风格控制\n- 歌词自定义\n- 音频扩展\n\n### 使用场景\n适合音乐创作、背景音乐制作等。\n\n### 优缺点\n- ✅ 音质出色\n- ✅ 风格控制精细\n- ❌ 平台较新\n- ❌ 国内需翻墙`,
    websiteUrl: "https://www.udio.com",
    category: "audio",
    tags: ["音乐", "生成", "音频", "创作"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.4,
    ratingCount: 3210,
    viewCount: 23456,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-04-10",
  },
  // ===== 编程 (coding) =====
  {
    id: "cursor",
    name: "Cursor",
    tagline: "AI驱动的代码编辑器，基于VS Code，支持智能补全、对话式编程和代码重构",
    description: `## Cursor 简介\n\nCursor 是一款基于 VS Code 的AI代码编辑器。\n\n### 核心功能\n- AI代码补全\n- 对话式编程\n- 代码重构\n- 多文件编辑\n\n### 使用场景\n适合所有开发者，特别是需要快速迭代的项目。\n\n### 优缺点\n- ✅ 与VS Code兼容\n- ✅ AI能力强大\n- ❌ Pro版较贵\n- ❌ 有时会产生幻觉`,
    websiteUrl: "https://cursor.sh",
    category: "coding",
    tags: ["编程", "IDE", "代码补全", "VS Code"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.8,
    ratingCount: 9876,
    viewCount: 87654,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-01",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    tagline: "GitHub与OpenAI合作的AI编程助手，实时代码建议和自动补全",
    description: `## GitHub Copilot 简介\n\nGitHub Copilot 是最早且最成熟的AI编程助手。\n\n### 核心功能\n- 实时代码补全\n- 多语言支持\n- 上下文理解\n- 测试生成\n\n### 使用场景\n适合日常编程、代码审查、学习新语言。\n\n### 优缺点\n- ✅ 补全质量高\n- ✅ IDE集成好\n- ❌ 需要订阅\n- ❌ 对私有库理解有限`,
    websiteUrl: "https://github.com/features/copilot",
    category: "coding",
    tags: ["Copilot", "GitHub", "代码补全", "编程"],
    pricingType: "paid",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.6,
    ratingCount: 12345,
    viewCount: 98765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-06-21",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    tagline: "Codeium推出的AI代码编辑器，提供流畅的AI编程体验和智能代码理解",
    description: `## Windsurf 简介\n\nWindsurf（原Codeium）是新一代AI代码编辑器。\n\n### 核心功能\n- 智能代码补全\n- AI对话编程\n- 代码库理解\n- 多语言支持\n\n### 使用场景\n适合需要免费AI编程工具的开发者。\n\n### 优缺点\n- ✅ 基础版免费\n- ✅ 补全速度快\n- ❌ 生态不如Copilot\n- ❌ 高级功能需付费`,
    websiteUrl: "https://codeium.com/windsurf",
    category: "coding",
    tags: ["Windsurf", "Codeium", "编程", "免费"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.4,
    ratingCount: 5432,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-11-13",
  },
  {
    id: "v0dev",
    name: "v0.dev",
    tagline: "Vercel推出的AI前端组件生成器，通过自然语言描述生成React组件代码",
    description: `## v0.dev 简介\n\nv0.dev 是 Vercel 推出的AI UI生成工具。\n\n### 核心功能\n- 自然语言生成UI组件\n- React + Tailwind CSS\n- 组件可直接复制使用\n- 迭代优化\n\n### 使用场景\n适合前端开发者快速原型设计。\n\n### 优缺点\n- ✅ 生成质量高\n- ✅ 代码可直接用\n- ❌ 仅限前端UI\n- ❌ 免费额度有限`,
    websiteUrl: "https://v0.dev",
    category: "coding",
    tags: ["v0", "前端", "UI", "React"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 6543,
    viewCount: 54321,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-10-12",
  },
  // ===== 搜索 (search) =====
  {
    id: "perplexity",
    name: "Perplexity",
    tagline: "AI驱动的智能搜索引擎，实时联网搜索并生成带引用来源的精准答案",
    description: `## Perplexity 简介\n\nPerplexity 是新一代AI搜索引擎。\n\n### 核心功能\n- AI问答式搜索\n- 实时联网\n- 引用来源标注\n- 追问深入\n\n### 使用场景\n适合研究、调研、事实查询等。\n\n### 优缺点\n- ✅ 引用来源透明\n- ✅ 信息时效性强\n- ❌ 国内需翻墙\n- ❌ Pro版较贵`,
    websiteUrl: "https://www.perplexity.ai",
    category: "search",
    tags: ["搜索", "问答", "引用", "研究"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.7,
    ratingCount: 7654,
    viewCount: 65432,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-12-07",
  },
  {
    id: "mita-search",
    name: "秘塔AI搜索",
    tagline: "国产AI搜索引擎，无广告干扰，直接给出结构化答案和信息来源",
    description: `## 秘塔AI搜索简介\n\n秘塔AI搜索是国产AI搜索引擎。\n\n### 核心功能\n- 无广告搜索\n- 结构化答案\n- 来源标注\n- 学术搜索模式\n\n### 使用场景\n适合中文信息检索、学术研究。\n\n### 优缺点\n- ✅ 国内直接可用\n- ✅ 无广告\n- ✅ 免费使用\n- ❌ 英文资源较少`,
    websiteUrl: "https://metaso.cn",
    category: "search",
    tags: ["搜索", "中文", "无广告", "学术"],
    pricingType: "free",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 5432,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-01-20",
  },
  {
    id: "phind",
    name: "Phind",
    tagline: "专为开发者设计的AI搜索引擎，精准解答编程问题并提供代码示例",
    description: `## Phind 简介\n\nPhind 是面向开发者的AI搜索引擎。\n\n### 核心功能\n- 编程问题解答\n- 代码示例生成\n- 技术文档搜索\n- 上下文追问\n\n### 使用场景\n适合开发者解决技术问题。\n\n### 优缺点\n- ✅ 编程领域精准\n- ✅ 免费使用\n- ❌ 非技术问题表现一般\n- ❌ 国内需翻墙`,
    websiteUrl: "https://www.phind.com",
    category: "search",
    tags: ["搜索", "编程", "开发者", "技术"],
    pricingType: "free",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.3,
    ratingCount: 3456,
    viewCount: 23456,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-02-14",
  },
  // ===== 办公 (office) =====
  {
    id: "gamma",
    name: "Gamma",
    tagline: "AI演示文稿生成工具，输入主题自动生成精美PPT，支持在线编辑",
    description: `## Gamma 简介\n\nGamma 是AI驱动的演示文稿工具。\n\n### 核心功能\n- AI生成PPT\n- 在线编辑\n- 多种模板\n- 一键排版\n\n### 使用场景\n适合快速制作演示文稿、汇报材料。\n\n### 优缺点\n- ✅ 生成速度快\n- ✅ 设计美观\n- ❌ 自定义受限\n- ❌ 免费版有水印`,
    websiteUrl: "https://gamma.app",
    category: "office",
    tags: ["PPT", "演示", "办公", "设计"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.5,
    ratingCount: 4567,
    viewCount: 34567,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-04-18",
  },
  {
    id: "chatpdf",
    name: "ChatPDF",
    tagline: "上传PDF文档即可与AI对话，快速提取文档关键信息和总结要点",
    description: `## ChatPDF 简介\n\nChatPDF 让你可以与PDF文档对话。\n\n### 核心功能\n- PDF文档问答\n- 内容总结\n- 关键信息提取\n- 多语言支持\n\n### 使用场景\n适合论文阅读、合同审查、报告分析。\n\n### 优缺点\n- ✅ 使用简单\n- ✅ 有免费额度\n- ❌ 大文件处理慢\n- ❌ 复杂表格识别一般`,
    websiteUrl: "https://www.chatpdf.com",
    category: "office",
    tags: ["PDF", "文档", "问答", "总结"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.2,
    ratingCount: 3456,
    viewCount: 28765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-02-05",
  },
  {
    id: "feishu-ai",
    name: "飞书智能伙伴",
    tagline: "飞书内置的AI助手，支持会议纪要生成、文档总结和智能日程管理",
    description: `## 飞书智能伙伴简介\n\n飞书智能伙伴是集成在飞书办公套件中的AI助手。\n\n### 核心功能\n- 会议纪要自动生成\n- 文档智能总结\n- 数据分析\n- 日程管理\n\n### 使用场景\n适合使用飞书的企业团队。\n\n### 优缺点\n- ✅ 与飞书深度集成\n- ✅ 国内直接可用\n- ❌ 依赖飞书生态\n- ❌ 企业版需付费`,
    websiteUrl: "https://www.feishu.cn/product/ai",
    category: "office",
    tags: ["飞书", "办公", "会议", "协作"],
    pricingType: "freemium",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 5678,
    viewCount: 38765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-11-21",
  },
  // ===== Agent =====
  {
    id: "coze",
    name: "扣子(Coze)",
    tagline: "字节跳动推出的AI Bot开发平台，零代码搭建个性化AI助手和工作流",
    description: `## 扣子(Coze)简介\n\nCoze 是字节跳动推出的AI Bot搭建平台。\n\n### 核心功能\n- 零代码Bot搭建\n- 插件市场\n- 工作流编排\n- 多渠道发布\n\n### 使用场景\n适合构建客服机器人、个人助手等。\n\n### 优缺点\n- ✅ 免费使用\n- ✅ 国内直接可用\n- ✅ 零代码\n- ❌ 高级功能有限制`,
    websiteUrl: "https://www.coze.cn",
    category: "agent",
    tags: ["Bot", "Agent", "工作流", "零代码"],
    pricingType: "free",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.4,
    ratingCount: 6789,
    viewCount: 54321,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-12-18",
  },
  {
    id: "dify",
    name: "Dify",
    tagline: "开源LLM应用开发平台，可视化编排AI工作流，支持RAG和Agent模式",
    description: `## Dify 简介\n\nDify 是开源的LLM应用开发平台。\n\n### 核心功能\n- 可视化工作流\n- RAG引擎\n- Agent编排\n- 多模型支持\n\n### 使用场景\n适合开发者构建AI应用。\n\n### 优缺点\n- ✅ 开源免费\n- ✅ 功能强大\n- ✅ 可私有部署\n- ❌ 上手有门槛`,
    websiteUrl: "https://dify.ai",
    category: "agent",
    tags: ["开源", "Agent", "RAG", "工作流"],
    pricingType: "opensource",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.6,
    ratingCount: 5432,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-05-15",
  },
  {
    id: "autogpt",
    name: "AutoGPT",
    tagline: "开源自主AI Agent框架，能够自动分解和执行复杂任务，实现目标驱动",
    description: `## AutoGPT 简介\n\nAutoGPT 是开源的自主AI Agent框架。\n\n### 核心功能\n- 自主任务分解\n- 目标驱动执行\n- 网络搜索\n- 文件操作\n\n### 使用场景\n适合自动化任务、研究探索等。\n\n### 优缺点\n- ✅ 完全开源\n- ✅ 概念先进\n- ❌ 运行不稳定\n- ❌ 消耗API额度大`,
    websiteUrl: "https://github.com/Significant-Gravitas/AutoGPT",
    category: "agent",
    tags: ["AutoGPT", "Agent", "自主", "开源"],
    pricingType: "opensource",
    isChinaAvailable: true,
    isChineseSupported: false,
    rating: 4.1,
    ratingCount: 8765,
    viewCount: 76543,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-30",
  },
  // ===== 开发 (dev) =====
  {
    id: "huggingface",
    name: "Hugging Face",
    tagline: "全球最大的AI模型社区和托管平台，提供数万个开源模型和数据集",
    description: `## Hugging Face 简介\n\nHugging Face 是最大的AI开源社区。\n\n### 核心功能\n- 模型托管与分享\n- 数据集仓库\n- Spaces应用部署\n- Transformers库\n\n### 使用场景\n适合AI研究者和开发者。\n\n### 优缺点\n- ✅ 开源模型丰富\n- ✅ 社区活跃\n- ✅ 免费托管\n- ❌ 国内访问慢`,
    websiteUrl: "https://huggingface.co",
    category: "dev",
    tags: ["模型", "开源", "社区", "托管"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.8,
    ratingCount: 11234,
    viewCount: 98765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-01-01",
  },
  {
    id: "replicate",
    name: "Replicate",
    tagline: "云端AI模型运行平台，一行代码调用数千个开源模型，按用量计费",
    description: `## Replicate 简介\n\nReplicate 让你轻松运行开源AI模型。\n\n### 核心功能\n- 一键运行开源模型\n- API调用\n- 按用量计费\n- 模型微调\n\n### 使用场景\n适合需要快速部署AI模型的开发者。\n\n### 优缺点\n- ✅ 使用简单\n- ✅ 模型丰富\n- ❌ 按用量计费可能贵\n- ❌ 国内访问慢`,
    websiteUrl: "https://replicate.com",
    category: "dev",
    tags: ["模型", "API", "云端", "部署"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.4,
    ratingCount: 3456,
    viewCount: 34567,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-06-15",
  },
  {
    id: "langchain",
    name: "LangChain",
    tagline: "流行的LLM应用开发框架，提供链式调用、记忆管理和工具集成能力",
    description: `## LangChain 简介\n\nLangChain 是最流行的LLM应用开发框架。\n\n### 核心功能\n- 链式调用编排\n- 记忆管理\n- 工具集成\n- RAG支持\n\n### 使用场景\n适合构建复杂的AI应用。\n\n### 优缺点\n- ✅ 生态丰富\n- ✅ 社区活跃\n- ✅ 开源免费\n- ❌ 学习曲线陡`,
    websiteUrl: "https://www.langchain.com",
    category: "dev",
    tags: ["框架", "LLM", "开发", "开源"],
    pricingType: "opensource",
    isChinaAvailable: true,
    isChineseSupported: false,
    rating: 4.5,
    ratingCount: 7654,
    viewCount: 65432,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2022-10-25",
  },
  // Extra tools to reach 36+
  {
    id: "tongyi",
    name: "通义千问",
    tagline: "阿里巴巴推出的大语言模型，支持对话、创作、编程等多种任务",
    description: `## 通义千问简介\n\n通义千问是阿里巴巴推出的大语言模型产品。\n\n### 核心功能\n- 多轮对话\n- 文档理解\n- 代码生成\n- 图像理解\n\n### 使用场景\n适合日常问答、办公辅助、开发支持。\n\n### 优缺点\n- ✅ 国内直接可用\n- ✅ 免费使用\n- ✅ 中文理解好\n- ❌ 英文能力较弱`,
    websiteUrl: "https://tongyi.aliyun.com",
    category: "chat",
    tags: ["通义", "阿里", "对话", "中文"],
    pricingType: "free",
    isChinaAvailable: true,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 6543,
    viewCount: 43210,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-04-07",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    tagline: "专业级AI图像生成平台，提供精细控制和游戏资产生成能力",
    description: `## Leonardo AI 简介\n\nLeonardo AI 是专业的AI图像生成平台。\n\n### 核心功能\n- 高质量图像生成\n- 游戏资产创建\n- 精细参数控制\n- 模型训练\n\n### 使用场景\n适合游戏开发、概念设计、插画创作。\n\n### 优缺点\n- ✅ 游戏资产出色\n- ✅ 控制精细\n- ❌ 免费额度少\n- ❌ 国内需翻墙`,
    websiteUrl: "https://leonardo.ai",
    category: "image",
    tags: ["绘画", "游戏", "资产", "设计"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.4,
    ratingCount: 4321,
    viewCount: 32100,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-01-25",
  },
  {
    id: "heygen",
    name: "HeyGen",
    tagline: "AI数字人视频生成平台，快速创建真人级别的虚拟主播和营销视频",
    description: `## HeyGen 简介\n\nHeyGen 是AI数字人视频生成平台。\n\n### 核心功能\n- 数字人视频生成\n- 口型同步\n- 多语言配音\n- 虚拟主播\n\n### 使用场景\n适合营销视频、培训课程、产品介绍。\n\n### 优缺点\n- ✅ 数字人逼真\n- ✅ 多语言支持\n- ❌ 价格较贵\n- ❌ 免费版限制多`,
    websiteUrl: "https://www.heygen.com",
    category: "video",
    tags: ["数字人", "视频", "营销", "AI主播"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 2345,
    viewCount: 21098,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-05-10",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    tagline: "浏览器中的AI全栈开发工具，通过对话式编程快速构建和部署Web应用",
    description: `## Bolt.new 简介\n\nBolt.new 是StackBlitz推出的AI开发工具。\n\n### 核心功能\n- 浏览器内开发\n- AI全栈生成\n- 一键部署\n- 实时预览\n\n### 使用场景\n适合快速原型开发、学习编程。\n\n### 优缺点\n- ✅ 无需本地环境\n- ✅ 部署方便\n- ❌ 复杂项目受限\n- ❌ 免费额度少`,
    websiteUrl: "https://bolt.new",
    category: "coding",
    tags: ["全栈", "浏览器", "部署", "Web"],
    pricingType: "freemium",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.3,
    ratingCount: 3210,
    viewCount: 28765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2024-10-01",
  },
  {
    id: "beautifulai",
    name: "Beautiful.ai",
    tagline: "AI智能PPT设计工具，自动排版和美化，让每一页幻灯片都专业精美",
    description: `## Beautiful.ai 简介\n\nBeautiful.ai 是AI驱动的演示文稿设计工具。\n\n### 核心功能\n- 智能排版\n- 设计模板库\n- 团队协作\n- 品牌一致性\n\n### 使用场景\n适合商务演示、方案汇报。\n\n### 优缺点\n- ✅ 设计精美\n- ✅ 自动排版\n- ❌ 需要付费\n- ❌ 国内访问慢`,
    websiteUrl: "https://www.beautiful.ai",
    category: "office",
    tags: ["PPT", "设计", "演示", "美化"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.3,
    ratingCount: 2345,
    viewCount: 19876,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-03-08",
  },
  {
    id: "gpts",
    name: "GPTs",
    tagline: "OpenAI推出的自定义GPT应用商店，创建和分享个性化的AI助手",
    description: `## GPTs 简介\n\nGPTs 是 OpenAI 的自定义 GPT 应用平台。\n\n### 核心功能\n- 自定义AI助手\n- 知识库上传\n- 工具集成\n- 应用商店\n\n### 使用场景\n适合创建垂直领域AI助手。\n\n### 优缺点\n- ✅ 定制灵活\n- ✅ 社区丰富\n- ❌ 需ChatGPT Plus\n- ❌ 国内无法使用`,
    websiteUrl: "https://chat.openai.com/gpts",
    category: "agent",
    tags: ["GPTs", "自定义", "应用商店", "OpenAI"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: true,
    rating: 4.2,
    ratingCount: 4567,
    viewCount: 38765,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-11-06",
  },
  {
    id: "resembleai",
    name: "Resemble AI",
    tagline: "专业AI语音克隆和合成平台，秒级创建逼真的自定义语音和音效",
    description: `## Resemble AI 简介\n\nResemble AI 是专业的语音克隆平台。\n\n### 核心功能\n- 实时语音克隆\n- 情感语音合成\n- API集成\n- 多语言支持\n\n### 使用场景\n适合游戏配音、视频制作、有声书等。\n\n### 优缺点\n- ✅ 克隆质量高\n- ✅ API好用\n- ❌ 价格较贵\n- ❌ 需英文使用`,
    websiteUrl: "https://www.resemble.ai",
    category: "audio",
    tags: ["语音克隆", "TTS", "配音", "音效"],
    pricingType: "paid",
    isChinaAvailable: false,
    isChineseSupported: false,
    rating: 4.2,
    ratingCount: 1234,
    viewCount: 12345,
    screenshots: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: "2023-04-20",
  },
];
