// 全量更新应用分类 - 按照用户提供的完整分类体系
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_SERVICE_KEY
);

// 完整的分类映射数据
const fullCategoryMapping = [
  // 对话类
  { name: '通义千问', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '文心一言', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '豆包', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '讯飞星火', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '腾讯元宝', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '智谱清言', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'DeepSeek', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '书生大模型', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '百川大模型', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '阶跃AI', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '天工AI', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '百小应', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '商量SenseChat', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '华为小艺', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '百灵大模型', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'LongCat', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'Z.ai', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'Qwen Chat', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'MiniMax', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '千问', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '魔搭GPT（ModelScopeGPT）', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '即梦AI', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'NLUI', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '逗逗AI', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'Kimi智能助手', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: 'Flowith', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '通义灵眸', main_category: 'chat', sub_category: 'chat_domestic' },
  { name: '问小白', main_category: 'chat', sub_category: 'chat_domestic' },
  
  { name: 'ChatGPT', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Claude', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Gemini', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Google Bard', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Microsoft Copilot', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Mistral AI', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Cohere AI', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Meta AI', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'AI21 Labs', main_category: 'chat', sub_category: 'chat_overseas' },
  { name: 'Stability AI', main_category: 'chat', sub_category: 'chat_overseas' },
  
  { name: 'Kimi', main_category: 'chat', sub_category: 'chat_general' },
  { name: '豆包', main_category: 'chat', sub_category: 'chat_general' },
  { name: '讯飞星火', main_category: 'chat', sub_category: 'chat_general' },
  { name: '腾讯元宝', main_category: 'chat', sub_category: 'chat_general' },
  { name: '通义千问', main_category: 'chat', sub_category: 'chat_general' },
  { name: '文心一言', main_category: 'chat', sub_category: 'chat_general' },
  { name: '智谱清言', main_category: 'chat', sub_category: 'chat_general' },
  { name: 'DeepSeek', main_category: 'chat', sub_category: 'chat_general' },
  { name: 'ChatGPT', main_category: 'chat', sub_category: 'chat_general' },
  { name: 'Claude', main_category: 'chat', sub_category: 'chat_general' },
  { name: 'Gemini', main_category: 'chat', sub_category: 'chat_general' },
  
  { name: 'Character.AI', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Bing新必应', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Poe', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '夸克AI', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '360智脑', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Replika', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Pi', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Inworld', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '钉钉·个人版', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Meta AI助手', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Koko AI', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '通义星尘', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'CueMe', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '造梦次元', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Museland', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '百度AI助手', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '小悟空', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '紫东太初', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '小黄蕉', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '冒泡鸭', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'J1 Assistant', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Cici', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Le Chat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '百度AI伙伴', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '超级助理', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Wanderboat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'MChat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Luca面壁露卡', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '元象XChat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'ChitChop', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Forefront', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'HuggingChat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'TigerBot', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Stable Chat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'ColossalChat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Jasper Chat', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'MOSS', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'YouChat AI', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'ChatSonic', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Whispr', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Open Assistant', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Neeva', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '对话写作猫', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '应事AI', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Me.bot', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'Saylo', main_category: 'chat', sub_category: 'chat_fun' },
  { name: 'TRAE', main_category: 'chat', sub_category: 'chat_fun' },
  { name: '秒哒', main_category: 'chat', sub_category: 'chat_fun' },

  // 写作类 - 文案创作
  { name: '秘塔写作猫', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Jasper', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Rytr', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Grammarly', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Writesonic', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '彩云小梦', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '火龙果写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '讯飞写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '稿定AI文案', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '魔撰写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Copy.ai', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'DeepL Write', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '有道写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '写作蛙', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '文思助手', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '爱改写', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'HeyFriday', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '易撰', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '讯飞绘文', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '笔灵AI写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '新华妙笔', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '讯飞文书', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '创一AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Muset', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '华文笔杆', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '松果AI写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '公文宝', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'PaperXie智能写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '迅捷AI写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '橙篇', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '深言达意', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '墨狐AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '灵犀速写', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '库宝AI工作助手', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '文状元', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '晓语台', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Jenni', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '有道翻译·AI写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Wordvice AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'AI新媒体文章', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '宙语Cosmos', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '灵构AI笔记', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '百度作家平台', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '爱创作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Verse', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Moonbeam', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Cohesive', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '万彩AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'WritingPal', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Magic Write', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '奇妙文', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Spell.tools', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'HyperWrite', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Typeface AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '悉语', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '文涌Effidit', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '树熊写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '智搜', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '创作王', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '字符狂飙', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'XPaper AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '悟智写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '讯飞智检', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '5118 SEO优化精灵', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'ContentBot', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Bearly', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '快文CopyDone', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Peppertype.ai', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Compose AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Texta', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'ClosersCopy', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Sudowrite', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'WPS智能写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Anyword', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Hypotenuse AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'ParagraphAI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'LongShot', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Jounce', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Reword', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Elephas', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'AISEO', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Writer', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'SurferSEO', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'ProWritingAid', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Yaara', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'WordTune', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Copysmith', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'NeuralText', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Frase', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Copymatic', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'TextCortex', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'INK', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Content at Scale', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'Mark Copy', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '蛙蛙写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'FlowUs AI', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '光速写作', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'WriteWise', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: '万能小in', main_category: 'writing', sub_category: 'writing_marketing' },
  { name: 'YouMind', main_category: 'writing', sub_category: 'writing_marketing' },

  // 写作类 - 论文学术
  { name: 'Paperpal', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '笔目鱼', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '稿易AI论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '千笔AI论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '66AI论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '维普科创助手', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '沁言学术', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '茅茅虫', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'GetDraft', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '掌桥科研AI论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'PaperBetter AI', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '小微智能论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '范文喵', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '笔杆论文', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'AI论文君', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'Smodin AI Research Paper', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'QuillBot', main_category: 'writing', sub_category: 'writing_academic' },
  { name: 'Rubriq', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '材料星AI', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '社研通', main_category: 'writing', sub_category: 'writing_academic' },
  { name: '量子探险', main_category: 'writing', sub_category: 'writing_academic' },

  // 写作类 - 小说网文
  { name: '笔灵AI小说', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '千页小说AI', main_category: 'writing', sub_category: 'writing_novel' },
  { name: 'NovelAI', main_category: 'writing', sub_category: 'writing_novel' },
  { name: 'MidReal', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '星火网文助手', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '小鱼AI写作', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '超级小说家', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '墨问', main_category: 'writing', sub_category: 'writing_novel' },
  { name: 'Loomi', main_category: 'writing', sub_category: 'writing_novel' },
  { name: 'FeelFish', main_category: 'writing', sub_category: 'writing_novel' },
  { name: '落笔AI写作', main_category: 'writing', sub_category: 'writing_novel' },
  { name: 'ReadPo', main_category: 'writing', sub_category: 'writing_novel' },

  // 写作类 - 文档解析
  { name: 'ChatPDF', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'QuotePDF', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'docs2skills', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'Notion AI', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'Gamma', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'ChatDOC', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'PDF.ai', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'Humata', main_category: 'writing', sub_category: 'writing_document' },
  { name: 'PandaGPT', main_category: 'writing', sub_category: 'writing_document' },
  { name: '司马阅', main_category: 'writing', sub_category: 'writing_document' },
  { name: '知我AI', main_category: 'writing', sub_category: 'writing_document' },

  // 视觉类 - 图像生成
  { name: 'Midjourney', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Civitai', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Stable Diffusion', main_category: 'image', sub_category: 'image_generation' },
  { name: '吐司AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '造点AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '可灵', main_category: 'image', sub_category: 'image_generation' },
  { name: '可灵AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '通义万相', main_category: 'image', sub_category: 'image_generation' },
  { name: '秒画', main_category: 'image', sub_category: 'image_generation' },
  { name: 'WHEE', main_category: 'image', sub_category: 'image_generation' },
  { name: '呜哩', main_category: 'image', sub_category: 'image_generation' },
  { name: 'insMind', main_category: 'image', sub_category: 'image_generation' },
  { name: '咖图AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '视觉工厂', main_category: 'image', sub_category: 'image_generation' },
  { name: '秒绘AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '妙话AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '炉米Lumi', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Krea AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Leonardo AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Firefly AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Playground AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Ideogram AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'SeaArt AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Luma AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '言之画', main_category: 'image', sub_category: 'image_generation' },
  { name: '百度智能云一念', main_category: 'image', sub_category: 'image_generation' },
  { name: '艾绘', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Graviti Diffus', main_category: 'image', sub_category: 'image_generation' },
  { name: '奇域AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '触手AI绘画', main_category: 'image', sub_category: 'image_generation' },
  { name: '造梦日记', main_category: 'image', sub_category: 'image_generation' },
  { name: '6pen Art', main_category: 'image', sub_category: 'image_generation' },
  { name: '画宇宙', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Visual Electric', main_category: 'image', sub_category: 'image_generation' },
  { name: '360智绘', main_category: 'image', sub_category: 'image_generation' },
  { name: '网易AI创意工坊', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Imagine with Meta', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Freepik AI Image Generator', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Stockimg AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '175FUN', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Stable Doodle', main_category: 'image', sub_category: 'image_generation' },
  { name: '行者AI美术', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Skybox AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '超能画布', main_category: 'image', sub_category: 'image_generation' },
  { name: '创客贴AI画匠', main_category: 'image', sub_category: 'image_generation' },
  { name: '秘塔捉捉猫', main_category: 'image', sub_category: 'image_generation' },
  { name: '稿定AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '简单AI', main_category: 'image', sub_category: 'image_generation' },
  { name: '摩笔马良', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Canva AI图像生成', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Bing Image Creator', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Adobe Firefly', main_category: 'image', sub_category: 'image_generation' },
  { name: 'IconGen', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Logo Diffusion', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Realibox AI', main_category: 'image', sub_category: 'image_generation' },
  { name: 'Poly', main_category: 'image', sub_category: 'image_generation' },
  { name: '志设', main_category: 'image', sub_category: 'image_generation' },

  // 视觉类 - 图像处理
  { name: 'AI改图神器', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Kira', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Photoroom', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Ribbet.ai', main_category: 'image', sub_category: 'image_editing' },
  { name: '悟空图像PhotoSir', main_category: 'image', sub_category: 'image_editing' },
  { name: '360智图', main_category: 'image', sub_category: 'image_editing' },
  { name: '像素蛋糕', main_category: 'image', sub_category: 'image_editing' },
  { name: '如果相机', main_category: 'image', sub_category: 'image_editing' },
  { name: 'ARC', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Cutout.Pro', main_category: 'image', sub_category: 'image_editing' },
  { name: 'remove.bg', main_category: 'image', sub_category: 'image_editing' },
  { name: 'MagicStudio', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Booltool', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Faceswapper', main_category: 'image', sub_category: 'image_editing' },
  { name: 'ClipDrop', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Vmake AI', main_category: 'image', sub_category: 'image_editing' },
  { name: 'DeepSwapper', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Kacha AI', main_category: 'image', sub_category: 'image_editing' },
  { name: 'PicTech AI', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Hotpot.ai', main_category: 'image', sub_category: 'image_editing' },
  { name: '万相营造', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Facet', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Relight', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Unscreen', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Picsart Aura', main_category: 'image', sub_category: 'image_editing' },
  { name: 'Glinky', main_category: 'image', sub_category: 'image_editing' },
  { name: 'ImageScore AI - 可解释图像质量评估系统', main_category: 'image', sub_category: 'image_editing' },

  // 视觉类 - 创意设计
  { name: '墨刀AI', main_category: 'image', sub_category: 'image_design' },
  { name: 'Figma AI', main_category: 'image', sub_category: 'image_design' },
  { name: '美图设计室', main_category: 'image', sub_category: 'image_design' },
  { name: '135 AI排版', main_category: 'image', sub_category: 'image_design' },
  { name: 'Holopix AI', main_category: 'image', sub_category: 'image_design' },
  { name: 'Pixso AI', main_category: 'image', sub_category: 'image_design' },
  { name: 'Recraft AI', main_category: 'image', sub_category: 'image_design' },
  { name: '创客贴AI', main_category: 'image', sub_category: 'image_design' },
  { name: '鹿班', main_category: 'image', sub_category: 'image_design' },
  { name: 'Magic Design', main_category: 'image', sub_category: 'image_design' },
  { name: '标小智LOGO生成器', main_category: 'image', sub_category: 'image_design' },
  { name: 'Looka', main_category: 'image', sub_category: 'image_design' },
  { name: 'Logoai', main_category: 'image', sub_category: 'image_design' },
  { name: 'Vectorizer.AI', main_category: 'image', sub_category: 'image_design' },
  { name: '阿里云智能logo设计', main_category: 'image', sub_category: 'image_design' },
  { name: 'Neural Canvas', main_category: 'image', sub_category: 'image_design' },
  { name: '小墨鹰编辑器', main_category: 'image', sub_category: 'image_design' },
  { name: 'PagePop', main_category: 'image', sub_category: 'image_design' },

  // 视觉类 - 视频数字人
  { name: 'Pika', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Runway', main_category: 'video', sub_category: 'video_generation' },
  { name: 'HeyGen', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Sora', main_category: 'video', sub_category: 'video_generation' },
  { name: '万兴播爆', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Kaiber', main_category: 'video', sub_category: 'video_generation' },
  { name: 'D-ID', main_category: 'video', sub_category: 'video_generation' },
  { name: '来画', main_category: 'video', sub_category: 'video_generation' },
  { name: '讯飞绘镜', main_category: 'video', sub_category: 'video_generation' },
  { name: '曦灵数字人', main_category: 'video', sub_category: 'video_generation' },
  { name: '讯飞虚拟人', main_category: 'video', sub_category: 'video_generation' },
  { name: 'DeepBrain', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Synthesia', main_category: 'video', sub_category: 'video_generation' },
  { name: '怪兽AI数字人', main_category: 'video', sub_category: 'video_generation' },
  { name: '奇妙元', main_category: 'video', sub_category: 'video_generation' },
  { name: '即构数智人', main_category: 'video', sub_category: 'video_generation' },
  { name: '白日梦', main_category: 'video', sub_category: 'video_generation' },
  { name: '必剪Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: '蝉镜', main_category: 'video', sub_category: 'video_generation' },
  { name: '场辞', main_category: 'video', sub_category: 'video_generation' },
  { name: '磁力开创', main_category: 'video', sub_category: 'video_generation' },
  { name: '堆友AI反应堆', main_category: 'video', sub_category: 'video_generation' },
  { name: '堆友AI视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '飞影数字人', main_category: 'video', sub_category: 'video_generation' },
  { name: '鬼手剪辑GhostCut', main_category: 'video', sub_category: 'video_generation' },
  { name: '海螺视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '花生AI', main_category: 'video', sub_category: 'video_generation' },
  { name: '绘蛙', main_category: 'video', sub_category: 'video_generation' },
  { name: '绘蛙AI视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '绘想', main_category: 'video', sub_category: 'video_generation' },
  { name: '绘影字幕', main_category: 'video', sub_category: 'video_generation' },
  { name: '即创', main_category: 'video', sub_category: 'video_generation' },
  { name: '阶跃视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '巨日禄', main_category: 'video', sub_category: 'video_generation' },
  { name: '开拍', main_category: 'video', sub_category: 'video_generation' },
  { name: '快剪辑', main_category: 'video', sub_category: 'video_generation' },
  { name: '快转字幕', main_category: 'video', sub_category: 'video_generation' },
  { name: '录咖', main_category: 'video', sub_category: 'video_generation' },
  { name: '萌动AI', main_category: 'video', sub_category: 'video_generation' },
  { name: '秒创', main_category: 'video', sub_category: 'video_generation' },
  { name: '妙播', main_category: 'video', sub_category: 'video_generation' },
  { name: '模力视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '魔珐星云', main_category: 'video', sub_category: 'video_generation' },
  { name: '内容特工队', main_category: 'video', sub_category: 'video_generation' },
  { name: '闪剪', main_category: 'video', sub_category: 'video_generation' },
  { name: '神笔马良', main_category: 'video', sub_category: 'video_generation' },
  { name: '腾讯混元AI视频', main_category: 'video', sub_category: 'video_generation' },
  { name: '团队快剪', main_category: 'video', sub_category: 'video_generation' },
  { name: '万彩微影', main_category: 'video', sub_category: 'video_generation' },
  { name: '万兴天幕', main_category: 'video', sub_category: 'video_generation' },
  { name: '雾象', main_category: 'video', sub_category: 'video_generation' },
  { name: '献丑AI', main_category: 'video', sub_category: 'video_generation' },
  { name: '寻光', main_category: 'video', sub_category: 'video_generation' },
  { name: '一起剪', main_category: 'video', sub_category: 'video_generation' },
  { name: '艺映AI', main_category: 'video', sub_category: 'video_generation' },
  { name: '元镜', main_category: 'video', sub_category: 'video_generation' },
  { name: '云幕同声', main_category: 'video', sub_category: 'video_generation' },
  { name: '造次', main_category: 'video', sub_category: 'video_generation' },
  { name: '智谱清影', main_category: 'video', sub_category: 'video_generation' },
  { name: 'A2E', main_category: 'video', sub_category: 'video_generation' },
  { name: 'AdsTurbo AI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Artflow', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Atoms', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Capsule', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Captions', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Clipfly', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Decohere', main_category: 'video', sub_category: 'video_generation' },
  { name: 'DomoAI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Dream Machine', main_category: 'video', sub_category: 'video_generation' },
  { name: 'DreamFace', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Duix', main_category: 'video', sub_category: 'video_generation' },
  { name: 'EbSynth', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Etna', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Filmora', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Fliki', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Flow Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Gatekeep', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Gencraft', main_category: 'video', sub_category: 'video_generation' },
  { name: 'GoEnhance', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Google Vids', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Haiper', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Hedra', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Higgsfield', main_category: 'video', sub_category: 'video_generation' },
  { name: 'HitPaw', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Hotshot', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Humva', main_category: 'video', sub_category: 'video_generation' },
  { name: 'InVideo AI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'JoyPix', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Kapwing', main_category: 'video', sub_category: 'video_generation' },
  { name: 'KomikoAI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'KreadoAI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'LensGo', main_category: 'video', sub_category: 'video_generation' },
  { name: 'LTX Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Lumen5', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Magicam', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Medeo', main_category: 'video', sub_category: 'video_generation' },
  { name: 'MochiAni', main_category: 'video', sub_category: 'video_generation' },
  { name: 'MOKI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Mootion', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Morph Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Noisee AI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'OneStory', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Opus Clip', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Pictory', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Pixfun', main_category: 'video', sub_category: 'video_generation' },
  { name: 'PixVerse', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Pollo AI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Rask', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Rephrase.ai', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Synthesys', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Spikes Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Stable Video', main_category: 'video', sub_category: 'video_generation' },
  { name: 'SteveAI', main_category: 'video', sub_category: 'video_generation' },
  { name: 'SkyReels', main_category: 'video', sub_category: 'video_generation' },
  { name: 'SWE-Model-Arena', main_category: 'video', sub_category: 'video_generation' },
  { name: 'TapNow', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Tavus', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Veed Video Background Remover', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Video Ocean', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Video Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Vidu', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Viggle', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Vimi', main_category: 'video', sub_category: 'video_generation' },
  { name: 'vivago.ai', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Vizard', main_category: 'video', sub_category: 'video_generation' },
  { name: 'VMagic', main_category: 'video', sub_category: 'video_generation' },
  { name: 'WinkStudio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Wonder Studio', main_category: 'video', sub_category: 'video_generation' },
  { name: 'YoYo', main_category: 'video', sub_category: 'video_generation' },
  { name: 'BgRem', main_category: 'video', sub_category: 'video_generation' },
  { name: 'AVCLabs', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Colossyan', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Colourlab.ai', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Elai.io', main_category: 'video', sub_category: 'video_generation' },
  { name: 'Hour One', main_category: 'video', sub_category: 'video_generation' },

  // 音频类 - 音乐生成
  { name: 'Suno', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Udio', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Soundraw', main_category: 'audio', sub_category: 'audio_composition' },
  { name: '网易天音', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Stable Audio', main_category: 'audio', sub_category: 'audio_composition' },
  { name: '天工SkyMusic', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Mubert', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Boomy', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Producer.ai', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Adobe Podcast', main_category: 'audio', sub_category: 'audio_composition' },
  { name: '海绵音乐', main_category: 'audio', sub_category: 'audio_composition' },
  { name: '天谱乐', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Lyrics Into Song AI', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Sonauto', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'SoundView', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Noiz AI', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Mureka', main_category: 'audio', sub_category: 'audio_composition' },
  { name: 'Tunee', main_category: 'audio', sub_category: 'audio_composition' },

  // 音频类 - 配音克隆
  { name: '魔音工坊', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '讯飞智作', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'ElevenLabs', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '琅琅配音', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'MiniMax Audio', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Keevx声音克隆', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '刺鸟配音', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Wondercraft', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '大饼AI变声', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '千音漫语', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '悦音配音', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'ACE Studio', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Audiobox', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'FakeYou', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Fryderyk', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'IBM Watson文字转语音', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'LOVO AI', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Murf AI', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'NaturalReader', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'RESEMBLE.AI', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Supertone Shift', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'TextToSpeech', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'TTSMaker', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Typecast', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Uberduck', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Veed AI Voice Generator', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Voice.ai', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Voicemaker', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Voicemod', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Voicenotes', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'WellSaid', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Speechify', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Play.ht', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'MetaVoice', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Clipchamp AI旁白生成器', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'OptimizerAI', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: 'Reecho睿声', main_category: 'audio', sub_category: 'audio_synthesis' },
  { name: '讯飞译制', main_category: 'audio', sub_category: 'audio_synthesis' },

  // 音频类 - 语音转写
  { name: '讯飞听见', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '通义听悟', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Notta', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Otter.ai', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'AssemblyAI', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'LALAL.AI', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Krisp', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '讯飞会议', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '飞书妙记', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '多维视界', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '简单听记', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '听脑AI', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: '音述AI', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Vemus未音', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Nafy AI', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'TurboScribe', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'NotebookLM', main_category: 'audio', sub_category: 'audio_transcription' },
  { name: 'Airgram', main_category: 'audio', sub_category: 'audio_transcription' },

  // 音频类 - 音频编辑
  { name: '网易云音乐·X Studio', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'Audo Studio', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'BeatBot', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'beatoven.ai', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '蓝藻AI', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'Deepgram', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '音潮', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '音虫', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '音疯', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '音剪', main_category: 'audio', sub_category: 'audio_editing' },
  { name: '音秘', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'MemoAI', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'Lemonaid', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'BGM猫', main_category: 'audio', sub_category: 'audio_editing' },
  { name: 'Descript', main_category: 'audio', sub_category: 'audio_editing' }
];

async function fullUpdateCategories() {
  console.log('开始全量更新应用分类...');
  console.log(`总计需要更新: ${fullCategoryMapping.length} 个应用`);
  
  let successCount = 0;
  let failCount = 0;
  const notFoundApps = [];
  const categoryStats = {};
  
  for (const app of fullCategoryMapping) {
    try {
      // 查找应用
      const { data: existingApp, error: findError } = await supabase
        .from('tools')
        .select('*')
        .eq('name', app.name)
        .single();
      
      if (findError || !existingApp) {
        console.log(`未找到应用: ${app.name}`);
        notFoundApps.push(app.name);
        failCount++;
        continue;
      }
      
      // 更新分类
      const { error: updateError } = await supabase
        .from('tools')
        .update({
          main_category: app.main_category,
          sub_category: app.sub_category,
          updated_at: new Date().toISOString()
        })
        .eq('name', app.name);
      
      if (updateError) {
        console.error(`更新应用 ${app.name} 失败:`, updateError);
        failCount++;
      } else {
        console.log(`✓ ${app.name} -> ${app.main_category}/${app.sub_category}`);
        successCount++;
        
        // 统计分类数量
        const key = `${app.main_category}/${app.sub_category}`;
        categoryStats[key] = (categoryStats[key] || 0) + 1;
      }
      
    } catch (error) {
      console.error(`处理应用 ${app.name} 时出错:`, error);
      failCount++;
    }
    
    // 每100个应用输出一次进度
    if ((successCount + failCount) % 100 === 0) {
      console.log(`已处理: ${successCount + failCount}/${fullCategoryMapping.length}`);
    }
  }
  
  console.log('\n=== 全量更新完成 ===');
  console.log(`成功更新: ${successCount} 个应用`);
  console.log(`更新失败: ${failCount} 个应用`);
  
  if (notFoundApps.length > 0) {
    console.log(`\n未找到的 ${notFoundApps.length} 个应用:`);
    notFoundApps.forEach(app => console.log(`- ${app}`));
  }
  
  console.log('\n=== 分类统计 ===');
  Object.entries(categoryStats)
    .sort((a, b) => b[1] - a[1])
    .forEach(([category, count]) => {
      console.log(`${category}: ${count} 个应用`);
    });
}

// 执行全量更新
fullUpdateCategories().catch(console.error);
